%% Written by Julie M. Schneider 10/4/2018,. Modified by Yi-Lun Weng 02/10/2020
% All resources can be found at: https://openwetware.org/wiki/Mass_Univariate_ERP_Toolbox:_within-subject_t-tests

%% Creating GND Variables for Mass Univariate Analyses
%If you already have a GND file:
load play_all_firstlook.GND -MAT

%%If chanlocs are wrong, load GND_chanlocs.mat
%GND.chanlocs = GND_chanlocs
%%To create a GND variable:
%GND=erplab2GND('gui')

%%%%%% Factorial analysis
%Define some variables
n_perm = 1e4;
chan_hood = 32;


%% Factorial mean time window analysis
%% Full factorial design
%% 0 ~ -100ms
time_wind = [-100 0];
%% Cluster method
GND = FclustGND(GND, ...
'bins', 25:27, ...
'factor_names', {'bias'}, ...
'factor_levels', [3], ...
'time_wind', time_wind,'mean_wind','yes',...
'n_perm', n_perm, ...
'plot_mn_topo', 'yes', ...
'save_GND', 'no', ...
'output_file', 'play_MUT_firstlook_factorial_anova_result.xlsx');

% %% fdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'save_GND', 'no');
% 
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% -100 ~ -200ms
% %% Cluster method
% time_wind = [-100 -200];
% GND = FclustGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind,'mean_wind','yes',...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% fdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'save_GND', 'no');
% 
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% 
% %% -200 ~ -300ms
% %% Cluster method
% time_wind = [-200 -300];
% GND = FclustGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind,'mean_wind','yes',...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% fdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'save_GND', 'no');
% 
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% -300 ~ -400ms
% %% Cluster method
% time_wind = [-300 -400];
% GND = FclustGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind,'mean_wind','yes',...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% fdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'save_GND', 'no');
% 
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% 
% %% Factorial time point by time point analysis
% %% Full factorial design
% 
% %% 0 ~ -400ms
% time_wind = [0 -400];
% %% Cluster method
% GND = FclustGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'chan_hood', chan_hood, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% tfdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'save_GND', 'no');
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% 0 ~ -100ms
% time_wind = [0 -100];
% %% Cluster method
% GND = FclustGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'chan_hood', chan_hood, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% fdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'save_GND', 'no');
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% -100 ~ -200ms
% time_wind = [-100 -200];
% %% Cluster method
% GND = FclustGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'chan_hood', chan_hood, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% fdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'save_GND', 'no');
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% 
% %% -200 ~ -300ms
% time_wind = [-200 -300];
% %% Cluster method
% GND = FclustGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'chan_hood', chan_hood, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% fdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'save_GND', 'no');
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% 
% %% -300 ~ -400ms
% time_wind = [-300 -400];
% %% Cluster method
% GND = FclustGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'chan_hood', chan_hood, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% fdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'save_GND', 'no');
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, ...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% 
% 
% %% -0 ~ -400ms
% %% Cluster method
% time_wind = [0 -400];
% GND = FclustGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind,'mean_wind','yes',...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');
% 
% %% fdr method
% GND = FfdrGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'save_GND', 'no');
% 
% 
% %% Fmax method
% GND = FmaxGND(GND, ...
% 'bins', 25:27, ...
% 'factor_names', {'bias'}, ...
% 'factor_levels', [3], ...
% 'time_wind', time_wind, 'mean_wind','yes',...
% 'n_perm', n_perm, ...
% 'save_GND', 'no');

%% Pair-wise follow-ups for verb bias effect
%Mod vs Inst bias
GND = FclustGND(GND, 'bins', [27, 26], ...  
                'factor_names', 'bias', ...  
                'factor_levels', 2, ...
                'time_wind', time_wind,'mean_wind','yes',...
                'n_perm', n_perm, ...
                'plot_mn_topo', 'yes', ...
                'save_GND', 'no', ...
                'output_file', 'play_Mod_Inst.xlsx');
%Mod vs Equi bias
GND = FclustGND(GND, 'bins', [27, 25], ...  
                'factor_names', 'bias', ...  
                'factor_levels', 2, ...
                'time_wind', time_wind,'mean_wind','yes',...
                'n_perm', n_perm, ...
                'plot_mn_topo', 'yes', ...
                'save_GND', 'no', ...
                'output_file', 'play_Mod_Equi.xlsx');
%Inst vs Equi bias
GND = FclustGND(GND, 'bins', [26, 25], ...  
                'factor_names', 'bias', ...  
                'factor_levels', 2, ...
                'time_wind', time_wind,'mean_wind','yes',...
                'n_perm', n_perm, ...
                'plot_mn_topo', 'yes', ...
                'save_GND', 'no', ...
                'output_file', 'play_Inst_Equi.xlsx');

%  %% Interaction follow-ups: Effect of bias at each level of action
% %Mod-bias
% GND = FclustGND(GND, 'bins', [1, 4], ...  
%                 'factor_names', 'action', ...  
%                 'factor_levels', 2, ...
%                 'time_wind', time_wind, ...
%                 'chan_hood', chan_hood, ...
%                 'n_perm', n_perm, ...
%                 'save_GND', 'yes', ...
%                 'output_file', 'play_action_mod.xlsx');
% %Inst-bias
% GND = FclustGND(GND, 'bins', [2, 5], ...  
%                 'factor_names', 'action', ...  
%                 'factor_levels', 2, ...
%                 'time_wind', time_wind, ...
%                 'chan_hood', chan_hood, ...
%                 'n_perm', n_perm, ...
%                 'save_GND', 'yes', ...
%                 'output_file', 'play_action_inst.xlsx');
% %Equi-bias
% GND = FclustGND(GND, 'bins', [3, 6], ...  
%                 'factor_names', 'action', ...  
%                 'factor_levels', 2, ...
%                 'time_wind', time_wind, ...
%                 'chan_hood', chan_hood, ...
%                 'n_perm', n_perm, ...
%                 'save_GND', 'yes', ...
%                 'output_file', 'play_action_equi.xlsx');
% 




